class android.os.AsyncTask$4 extends java.util.concurrent.FutureTask
{
    final android.os.AsyncTask this$0;

    void <init>(android.os.AsyncTask, java.util.concurrent.Callable)
    {
        android.os.AsyncTask$4 r0;
        android.os.AsyncTask r1;
        java.util.concurrent.Callable r2;

        r0 := @this: android.os.AsyncTask$4;

        r1 := @parameter0: android.os.AsyncTask;

        r2 := @parameter1: java.util.concurrent.Callable;

        r0.<android.os.AsyncTask$4: android.os.AsyncTask this$0> = r1;

        specialinvoke r0.<java.util.concurrent.FutureTask: void <init>(java.util.concurrent.Callable)>(r2);

        return;
    }

    protected void done()
    {
        android.os.AsyncTask$4 r0;
        android.os.AsyncTask $r1, $r5;
        java.lang.Object $r2;
        java.lang.Throwable $r3, $r4, $r6, $r8;
        java.lang.RuntimeException r12;
        java.util.concurrent.ExecutionException r13;

        r0 := @this: android.os.AsyncTask$4;

     label1:
        $r1 = r0.<android.os.AsyncTask$4: android.os.AsyncTask this$0>;

        $r2 = virtualinvoke r0.<android.os.AsyncTask$4: java.lang.Object get()>();

        staticinvoke <android.os.AsyncTask: void access$800(android.os.AsyncTask,java.lang.Object)>($r1, $r2);

     label2:
        goto label6;

     label3:
        $r4 := @caughtexception;

        $r5 = r0.<android.os.AsyncTask$4: android.os.AsyncTask this$0>;

        staticinvoke <android.os.AsyncTask: void access$800(android.os.AsyncTask,java.lang.Object)>($r5, null);

        goto label6;

     label4:
        $r6 := @caughtexception;

        r12 = new java.lang.RuntimeException;

        r13 = (java.util.concurrent.ExecutionException) $r6;

        $r8 = virtualinvoke r13.<java.util.concurrent.ExecutionException: java.lang.Throwable getCause()>();

        specialinvoke r12.<java.lang.RuntimeException: void <init>(java.lang.String,java.lang.Throwable)>("An error occurred while executing doInBackground()", $r8);

        throw r12;

     label5:
        $r3 := @caughtexception;

        staticinvoke <android.util.Log: int w(java.lang.String,java.lang.Throwable)>("AsyncTask", $r3);

     label6:
        return;

        catch java.lang.InterruptedException from label1 to label2 with label5;
        catch java.util.concurrent.ExecutionException from label1 to label2 with label4;
        catch java.util.concurrent.CancellationException from label1 to label2 with label3;
    }
}
